### ISSUE TITLE
smex default bind to M-x

### ISSUE THREAD

**Issue by cg505** [kotct/kotct.emacs#4]
By default there is no `(global-set-key (kbd "M-x") 'smex)` except in my local config. Is there a reason for that?

**Comment by cg505** [comment]
Part of the problem is that it's impossible to jump onto the rolling ball that is your configuration. I tried to do that with this project, essentially pulling your latest config in and then adding on to that, but I believe your emacs configuration changes the most and was long departed by the time you noticed that this existed. So I think what needs to happen is you should copy your config into this repo and start using it, and we can develop on top of your changing config. Essentially, a complete, exact copy of your config would be a good starting point for this repository IMO.

**Comment by rye** [comment]
Does that mean that you are suggesting completely obliterating everything and dumping my current configuration into here? I'd suggest changing the repository title in that case, but if we did that I'd definitely be using this one (collaboration is enticing), and then I'd remove my own and work on this configuration as my primary.  Then, this configuration can roll. I'm just worried that my preferences will not be congruent with those of others. We can work out a user config directory.

**Comment by cg505** [comment]
Yes. I can copy in the user config stuff once you've done that.
And obviously don't obliterate this, but rename it with -old or something.

**Comment by rye** [comment]
Yeah, I'll rename it to -old and then make a .emacs.d repository, dumping my stuff in there.

**Comment by rye** [comment]
Okay, I am doing this now. This won't break existing urls, but you should change them.
