### ISSUE TITLE
sam

### ISSUE THREAD

**Issue by cg505** [kotct/kotct.emacs#6]
@samontea and @Sammidysam both use the frustrating login of "sam". This prevents the login-based username detection from working properly. The solution is to allow specification of just a login name or a pair of a login name and a host.

**Comment by Sammidysam** [comment]
I like the host idea.  They can just be checked after the login name check corresponds to two items.

-Sam, sent on his iPod. You should be proud of him; typing on that thing is hard.

**Comment by samontea** [comment]
I as well like this idea. I'll work on this tomorrow, and push it to a branch for @Sammidysam to check.

**Comment by samontea** [comment]
solved by commit 743cc363
